name: Build & Deploy E-commerce app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 21

      - name: Build the application
        run: |
          mvn -B package --file pom.xml
          
      - name: Login to Heroku
        run: echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_EMAIL" --password-stdin registry.heroku.com
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Build and push to Heroku
        run: |
          docker build -t registry.heroku.com/ecommerce-boutique-demo/web .
          docker push registry.heroku.com/ecommerce-boutique-demo/web

      - name: Release to Heroku
        run: |
          heroku container:release web --app ecommerce-boutique-demo
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
